name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@ttgf0p2
        with:
          pdk: gf180mcuD

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@ttgf0p2

  gl_test:
    needs: gds
    strategy:
      matrix:
        target:
          - core
          - prog
          - peri_num_2
          - peri_num_3
          - peri_num_4
          - peri_num_5
          - peri_num_6
          - peri_num_7
          - peri_num_8
          - peri_num_9
          - peri_num_10
          - peri_num_11
      fail-fast: false
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: GL test
        uses: MichaelBell/tt-gds-action/gl_test@ttgf0p2
        with:
          make-targets: ${{ matrix.target }}

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@ttgf0p2
